version: '3.7'
services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: test-repo2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    network_mode: bridge
