/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Ki2WdvkkZc0
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { CardTitle, CardHeader, CardContent, Card } from "src/components/ui/card"

export function Component() {
  return (
    <Card className="w-full max-w-xs">
      <img alt="Product" className="aspect-[1.6]" height="250" src="/placeholder.svg" width="400" />
      <CardHeader className="p-4">
        <CardTitle className="text-2xl">Product Name</CardTitle>
      </CardHeader>
      <CardContent className="p-4">
        <p className="text-2xl font-semibold">$199.00</p>
      </CardContent>
    </Card>
  )
}
